### ISSUE TITLE
Adding a new external component (components.yaml)

### ISSUE THREAD

**Issue by jing-guo** [GEOS-ESM/GEOSana_GridComp#73]
I need to add a new external component @JCSDA_crtm/ into GEOSadas fixture, as a step to closely associate the old @NCEP_shared/NCEP_crtm/ to a living JCSDA component repository.

It was done easily before (pre-mepo time) through Externals.cfg through explicit parameters "remote=<URL>" and corresponding "local=<@JCSDA_crtm>".  However, there is no explicit <URL> in the new mepo components.yaml file anymore, but a short notation of relative path, e.g. "remote: ../MOM6.git".

Any advice to proceed for a correct solution for this problem?

**Comment by mathomp4** [comment]
@jing-guo You can put a full path in `components.yaml`. Right now you see things like:
```yaml
MAPL:
  local: ./src/Shared/@MAPL
  remote: ../MAPL.git
  tag: v2.12.1
  develop: develop
```
That "short" notation is from Git Submodule notation where it means if you clone GEOSgcm with, say, the SSH URL, `git@github.com:GEOS-ESM/GEOSgcm.git`, then it uses the SSH URL as well and clones `git@github.com:GEOS-ESM/GEOSgcm.git/../MAPL.git` or `git@github.com:GEOS-ESM/MAPL.git`. Likewise, if you use an HTTPS URL, then mepo clones all the subrepos with HTTPS URLs.

This makes it easy to support places where SSH urls aren't useful (aka Amazon Web Services or Docker containers)

Now, we can use the relative URLs since we usually fork *all* our sub-repos into GEOS-ESM. But you can also add your own, so if you had:
```yaml
MAPL:
  local: ./src/Shared/@MAPL
  remote: https://github.com/NOAA-EMC/JCSDA_CRTM.git
  tag: v2.12.1
  develop: develop
``` 
it would clone the NOAA-EMC repo for JCSDA_CRTM into the directory path of MAPL. I don't suggest doing this, but mepo will not stop you!

If you want to use a relative URL, then we could fork JCSDA_crtm into GEOS-ESM and then...there you go. It's in GEOS-ESM, so a relative URL will work.
